version: '3.7'
services:
  fortnite-reminder:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "fortnite-reminder"
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      TELEGRAM_TOKEN: ""
      TELEGRAM_CHAT_ID: ""
      TZ: "America/Sao_Paulo"
      REMINDER_ITEMS: "EID_KitchenNavigator"
